app/project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, TextAreaField, IntegerField, FieldList, Form, FormField
from wtforms.validators import  ValidationError, DataRequired, Email, EqualTo
from app.models import User, Project

class NewProjectForm(FlaskForm):
	title = StringField('Project Title', validators=[DataRequired()])
	submit = SubmitField('Create Project')

class RenameProjectForm(FlaskForm):
	title = StringField('Project Title', validators=[DataRequired()])
	submit = SubmitField('Rename Project')

class DeleteForm(FlaskForm):
	password = PasswordField('Enter Your Password', validators=[DataRequired()])
	submit = SubmitField('Delete Project')

class OutlineForm(FlaskForm):
	sources = TextAreaField('Sources')
	freewrite = TextAreaField('Freewrite')
	question = TextAreaField('Question')
	thesis = TextAreaField('Thesis')
	outline = TextAreaField('Outline')
	num_sections = IntegerField('Number of Sections')
	submit = SubmitField('Save Outline')

class EditSectionsForm(FlaskForm):
	submit = SubmitField('Save Draft')
	pass

class LineEditorForm(FlaskForm):
	title = StringField('Section Title')
	sentences = FieldList(TextAreaField('Sentence'))
	submit = SubmitField('Save Section')

class SectionTextEditorForm(FlaskForm):
	title = StringField('Section Title')
	text = TextAreaField('Text')
	submit = SubmitField('Save Section')

app/project/__init__.py
from flask import Blueprint

project = Blueprint('project', __name__, static_folder='static')

from . import views

app/project/views.py
from flask import render_template, redirect, url_for, flash, request, json
from flask_login import current_user, login_required
from .forms import NewProjectForm, DeleteForm, OutlineForm, EditSectionsForm, LineEditorForm, SectionTextEditorForm, RenameProjectForm
from werkzeug.security import check_password_hash 
from app.models import User, Project, Section
from wtforms import TextAreaField, StringField
from app import db, max_sections
from datetime import datetime
from app.email import export_draft_email

# for nlp
import spacy
import re
from collections import Counter
import numpy as np
import textstat

from .analyzer import get_length_distribution, get_reading_level
from . import project

import math

@project.route('/dashboard')
@login_required
def dashboard():
	projects = current_user.projects.order_by(Project.last_edit.desc()).all()
	return render_template('project/dashboard.html', projects=projects, title='Dashboard')

@project.route('/new_project', methods=['GET', 'POST'])
@login_required
def new_project():
	form = NewProjectForm()

	if form.validate_on_submit():
		project = Project(title=form.title.data, user_id=current_user.id, stage=1, timestamp=datetime.utcnow())
		db.session.add(project)
		db.session.commit()

		return redirect(url_for('project.project_dashboard', proj_id=project.id))

	return render_template('project/new_project.html', form=form, title='New Project')

@project.route('/project_dashboard/<proj_id>', methods=['GET','POST'])
@login_required
def project_dashboard(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	return render_template('project/project_dashboard.html', project=project, title='{}'.format(project.title))

@project.route('/progress/<proj_id>')
@login_required
def progress(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))

	stage = project.stage 
	project.stage = int(stage)+1
	db.session.commit()
	return redirect(url_for('project.project_dashboard', proj_id=project.id))

@project.route('rename_project/<proj_id>', methods=['GET', 'POST'])
@login_required
def rename_project(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	
	form = RenameProjectForm()

	if form.validate_on_submit():
		project.title = form.title.data
		db.session.commit()
		flash('Project Renamed', 'success')
		return redirect(url_for('project.project_dashboard', proj_id=project.id))
	return render_template('project/rename_project.html', project=project, form=form)

@project.route('/outline/<proj_id>', methods=['GET','POST'])
@login_required
def outline(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	form = OutlineForm()
	if form.validate_on_submit():
		project.sources = form.sources.data
		project.freewrite = form.freewrite.data
		project.question = form.question.data
		sections = Section.query.filter_by(project_id=project.id).order_by(Section.order)

		if form.num_sections.data < project.num_sections:
			difference = project.num_sections - form.num_sections.data
			rev_sections = Section.query.filter_by(project_id=project.id).order_by(Section.order.desc())
			i = 0
			while i < difference:
				to_delete = rev_sections.first()
				db.session.delete(to_delete)
				i += 1

		elif form.num_sections.data > project.num_sections:
			difference = form.num_sections.data - project.num_sections
			i = project.num_sections + 1
			diff_counter = difference
			while diff_counter > 0:
				section = Section(
					project_id=project.id,
					parent_type="draft",
					order=sections.count()+1,
					title='Section ' + str(sections.count()+1)
				)
				db.session.add(section)
				i += 1
				diff_counter -= 1
		else:
			pass		

		project.num_sections = form.num_sections.data
		project.thesis = form.thesis.data
		project.outline = form.outline.data
		project.last_edit = datetime.utcnow()
		db.session.commit()
		flash('Outline Saved', 'success')
		return redirect(url_for('project.project_dashboard', proj_id=project.id))
	return render_template('project/outline.html', 
							project=project, 
							title='Outline: {}'.format(project.title), 
							form=form,
							max_sections=max_sections)

@project.route('/first_draft/<proj_id>', methods=['GET', 'POST'])
@login_required
def first_draft(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))

	sections = Section.query.filter_by(project_id=project.id).order_by(Section.order)
	class F(EditSectionsForm):
		pass

	num_sections = project.num_sections
	record = {}

	i = 1
	while i <= num_sections:
		record.update({'{}'.format(str(i)):'Section {}'.format(str(i))})
		i += 1
	
	for key, value in record.items():
		setattr(F, key, TextAreaField(value))

	form = F()
	
	if form.validate_on_submit():
		for key, value in record.items():
			section = sections.filter_by(order=key).first()
			data = getattr(form, key).data
			section.text = data
		project.last_edit = datetime.utcnow()
		db.session.commit()
		flash('First Draft Saved', 'success')
		return redirect(url_for('project.project_dashboard', proj_id=project.id))

	return render_template(
		'project/first_draft.html', 
		project=project, sections=sections, 
		form=form, 
		record=record,
		title='First Draft: {}'.format(project.title)
	)

@project.route('/draft_editor/<proj_id>', methods=['GET', 'POST'])
@login_required
def draft_editor(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	sections = Section.query.filter_by(project_id=project.id).order_by(Section.order).all()


	return render_template('project/draft_editor.html', title='Draft Editor', project=project, sections=sections)

@project.route('new_section/<proj_id>', methods=['GET', 'POST'])
@login_required
def new_section(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	
	if project.sections.count() <= max_sections:
		new_section_order = Section.query.filter_by(project_id=project.id).order_by(Section.order.desc()).first().order + 1
		section = Section(
			project_id=project.id,
			order=new_section_order,
			title='Section ' + str(new_section_order)
		)
		db.session.add(section)
		db.session.commit()
		return redirect(url_for('project.draft_editor', proj_id=project.id))
	else:
		flash('Maximum number of sections reached', 'info')
		return redirect(url_for('project.draft_editor', proj_id=project.id))


@project.route('/line_editor/<proj_id>/<section_id>', methods=['GET', 'POST'])
@login_required
def line_editor(proj_id, section_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))

	def cleanhtml(raw_html):
		cleanr = re.compile('<.*?>')
		cleantext = re.sub(cleanr, '', raw_html)
		return cleantext

	section = Section.query.get(int(section_id))
	if section.project.user_id != current_user.id:
		return redirect(url_for('project.dashboard'))


	nlp = spacy.load('en_core_web_sm')
	doc = nlp(cleanhtml(section.text))
	sentences = [sent for sent in doc.sents]
	
	form = LineEditorForm()

	for sentence in sentences:
		form.sentences.append_entry()

	combo = zip(sentences, form.sentences)
	
	if form.validate_on_submit():
		flash('Section Saved', 'success')
		project.last_edit = datetime.utcnow()
		compiled = ''
		for sentence in form.sentences:
			if sentence.data is not None:
				compiled += sentence.data + ' '
			section.text = compiled
			section.title = form.title.data
			db.session.commit()

		return redirect(url_for('project.draft_editor', proj_id=project.id))

	return render_template('project/line_editor.html', 
							title='Line Editor', 
							sentences=sentences, 
							section=section,
							project=project, 
							combo=combo,
							form=form)
	
@project.route('/section_text_editor/<proj_id>/<section_id>', methods=['GET', 'POST'])
@login_required
def section_text_editor(proj_id, section_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))

	section = Section.query.get(int(section_id))
	if section.project.user_id != current_user.id:
		return redirect(url_for('project.dashboard'))

	form = SectionTextEditorForm()

	if form.validate_on_submit():
		project.last_edit = datetime.utcnow()
		section.title = form.title.data
		section.text = form.text.data
		db.session.commit()
		flash('Section Saved', 'success')
		return redirect(url_for('project.draft_editor', proj_id=project.id))

	return render_template('project/section_text_editor.html', 
							title='Full Text Editor',
							section=section, 
							project=project, 
							form=form)

@project.route('/draft_viewer/<proj_id>')
@login_required
def draft_viewer(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	
	sections = Section.query.filter_by(project_id=project.id).order_by(Section.order).all()

	return render_template('project/draft_viewer.html', project=project, sections=sections)

@project.route('/export_draft/<proj_id>')
@login_required
def export_draft(proj_id):
	project = Project.query.get(int(proj_id))
	if current_user.id != project.user_id:
		return redirect(url_for('project.dashboard'))
	sections = Section.query.filter_by(project_id=project.id).order_by(Section.order).all()
	export_draft_email(current_user, project.title, sections)
	flash('Your draft was sent to your email. Check your spam folder if it is missing.', 'info')
	return redirect(url_for('project.draft_editor', proj_id=project.id))

	

app/templates/project/dashboard.html
{% extends 'project/project_base.html' %}
{% block content %}
<link rel='stylesheet' href="{{ url_for('project.static', filename='style.css') }}">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current='page'>Dashboard</li>
  </ol>
</nav>
<div class='container mt-5'>
  <div class='row'>
    <div class='col-sm'></div>
    <div class='col-sm-8'>
      <div class="title-content">
        <h2 class='heading'>{{ current_user.first_name }}'s Projects</h2>
      </div>

      <hr>
      {% for project in projects %}
      <div class="card card-border">
        <div class="card-header text-muted">
          Status: In Progress
        </div>
        <div class="card-body">
          
          <h4 class="card-title">{{ project.title }}</h4>
          
          <p class="card-text">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-calendar3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"/>
              <path fill-rule="evenodd" d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
            Last Edit: {{ moment(project.last_edit).calendar() }} | Created:
            {{ moment(project.timestamp).fromNow() }}
          </p>
          <a href="{{ url_for('project.project_dashboard', proj_id=project.id) }}" class="btn btn-primary">
            Open Project
          </a>
        </div>
      </div>
      {% endfor %}
      <div class="card card-border">
        <div class="card-header">
          
        </div>
        <div class="card-body">
          <h4 class="card-title">Create a New Project</h4>
          <p class="card-text">Start a new work in progress.</p>
          <a href="{{ url_for('project.new_project') }}" class="btn btn-primary">
            New Project
          </a>
        </div>
      </div>
    </div>
    <div class='col-sm'></div>
  </div>
</div>

<script type='text/javascript'>
  $('.project-container').hover(function () {
    $('.project-container').removeClass('selected');
    $(this).addClass('selected');
  })
</script>

{% endblock content %}

app/templates/project/delete.html
{% extends 'project/project_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}


<div class='container mt-5'>
	<div class='row'>
		<div class='col-sm'></div>
		<div class='col-sm-6'>
			<div class="form-content">
				<h1>Delete</h1>
				<p class='lead'>
					Are you sure you want to delete <strong>{{ item.title }}</strong>?
					This cannot be undone.
				</p>
				{{ wtf.quick_form(form, button_map={'submit':'btn btn-danger'}) }}
				
			</div>
		</div>
		<div class='col-sm'></div>
	</div>
</div>
<style type='text/css'>
	.form-content {
		background-color: white;
		padding: 40px 40px 40px 40px;
		border-radius: 20px;
		border: 1px solid lightgray;
	}

	body {
		background: #FF416C;
		/* fallback for old browsers */
		background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
		/* Chrome 10-25, Safari 5.1-6 */
		background: linear-gradient(to right, #FF4B2B, #FF416C);
		/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

	}
</style>


{% endblock content %}

app/templates/project/draft_editor.html
{% extends 'project/project_base.html' %}

{% block content %}
<link rel='stylesheet' href="{{ url_for('project.static', filename='style.css') }}">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('project.dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item"><a
        href="{{ url_for('project.project_dashboard', proj_id=project.id) }}">{{ project.title }}</a></li>
    <li class="breadcrumb-item active" aria-current='page'>Draft Editor</li>
  </ol>
</nav>
<div class='container mt-5'>
  <div class='row'>
    <div class='col-sm'>
    </div>
    <div class='col-sm-8'>
      <div class="title-content mb-4">
        <h2 class='heading'>{{ project.title }}: Draft Editor </h2>
        <div class="dropdown ddown">
          <button class="btn btn-light mb-2 btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{ url_for('project.statistics', proj_id=project.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon icon bi bi-bar-chart-line" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1v-3a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3h1V7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7h1V2zm1 12h2V2h-2v12zm-3 0V7H7v7h2zm-5 0v-3H2v3h2z"/>
              </svg>
              Statistics
            </a>
            <a class="dropdown-item" href="{{ url_for('project.draft_viewer', proj_id=project.id) }}">
              
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-printer" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M11 2H5a1 1 0 0 0-1 1v2H3V3a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2h-1V3a1 1 0 0 0-1-1zm3 4H2a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h1v1H2a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1z"/>
                <path fill-rule="evenodd" d="M11 9H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1zM5 8a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H5z"/>
                <path d="M3 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
              </svg>
              Printable Version
            </a>
            <a href="{{ url_for('project.export_draft', proj_id=project.id) }}" class="dropdown-item">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-envelope" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
              </svg>
              Export Via Email
            </a>
          </div>
        </div>
      </div>

      {% for section in sections %}
      <div class="title-content mb-4">
        <h4>{{ section.title }}</h4>
        <p>{{ section.text|safe }}</p>
        {% if section.text == '' %}<p>You haven't written anything in this section yet.</p>{% endif %}
        <div class="dropdown">
          <button class="btn btn-sm btn-light dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class=" icon bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
            Edit Outline
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item"
              href="{{ url_for('project.section_text_editor', proj_id=project.id, section_id=section.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-file-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H4z"/>
                <path fill-rule="evenodd" d="M4.5 10.5A.5.5 0 0 1 5 10h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 8h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zm0-2A.5.5 0 0 1 5 4h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
              </svg>
              Full Text Editor
            </a>
            {% if section.text != '' %}
            <a class="dropdown-item"
              href="{{ url_for('project.line_editor', proj_id=project.id, section_id=section.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
              </svg>
              Line Editor
            </a>
            {% endif %}
            {% if project.sections.count() != 1 %}  
            <a class="dropdown-item" href="{{ url_for('project.delete', type='section', id=section.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="icon bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg>
              Delete Section
            </a>
            {% endif %}
          </div>
        </div><br>
      </div>
      {% endfor %}
      <div class="title-content mb-4">
        <h4>Create a New Section</h4>
        <a href="{{ url_for('project.new_section', proj_id=project.id) }}" class="btn btn-primary mb-2 mt-2">
          Create Section
        </a>
      </div>
    </div>
    <div class='col-sm'></div>
  </div>
</div>
{% endblock %}

app/templates/project/draft_viewer.html
{% extends 'project/project_base.html' %}
{% block content %}

<div class='container mt-5'>
  <div class='row'>
    <div class='col-sm'>
    </div>
    <div class='col-sm-8'>
      <div class='title-content'>
        <p>{{current_user.first_name}} {{current_user.last_name}}</p>
        <p>{{ moment(project.last_edit).format('MMMM Do, YYYY') }}</p>
        <p class="text-center">{{ project.title }}</p>
        {% for section in sections %}
        <strong>{{ section.title|safe }}</strong>
        <p>{{ section.text|safe }}</p>
        {% endfor %}
      </div>

    </div>
    <div class='col-sm'></div>
  </div>
</div>
<script>
  $( 'nav' ).hide();
</script>
{% endblock %}

app/templates/project/export_draft.html
<h1>{{ title }}</h1>
{% for section in sections %}
<h4>{{ section.title|safe }}</h4> 
<p>{{ section.text|safe }}</p>
{% endfor %}

app/templates/project/project_base.html
{% extends 'base.html' %}

{% block script %}
<script type='text/javascript'>
    $('#projects_nav').addClass('active')
</script>
{% endblock %}